name: 'Deploy app to App Engine on GCP'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  'build-and-deploy-app':
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./app
    env:
      VITE_BACKEND_ENDPOINT_URL: ${{ secrets.BACKEND_ENDPOINT_URL }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: npm ci

      - name: Building the application
        run: npm run build

      - name: Authenticating towards GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploying the application to GCP
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          working_directory: ./app
