name: 'Deploy to App Engine on GCP'

on:
  push:
    branches:
      - 'main'

jobs:
  'build-and-deploy':
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        run: npm run test

      - name: Building the application
        run: npm run build

      - name: Deploying the application to GCP
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Logging the URL
        run: gcloud app describe